### ISSUE TITLE
Init Command - update location of credentials file, make sure functionality exists (currently missing git support), change structure of the file to support multiple projects

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#135]
From file format document:

credentials.yml format:
This file would be created by init and contain credentials to access various services, keyed by project name.
`~/.zero/credentials.yml`
```
my-project:
- aws:
  - accessKeyId: AKIAABCD
  - secretAccessKey: ZXCV
- circleci:
  - apiKey: "1234"
- github:
  - accessToken: "0987"
another-project:
- github:
  - accessToken: "654"
```
