### ISSUE TITLE
Set K8s secrets for Cloudfront signed URL downloads

### ISSUE THREAD

**Issue by GrooveStomp** [commitdev/zero#273]
# Context
We want to set an environment variable with the Cloudfront signing key so we can generate signed URL downloads for the Zero client.

# Change
- Set the new backend service namespace appropriately.
See example for DB service here:
https://github.com/commitdev/zero-aws-eks-stack/blob/main/templates/kubernetes/terraform/modules/kubernetes/database-service.tf#L5-L9

- Add Terraform to set the K8s secret from AWS Secrets Manager (zero-aws-eks-stack):

- Set the k8s secrets in `<new-be-service>/templates/kubernetes/base/deployment.yml`
```
- name: CF_KEYPAIR_ID
  valueFrom:
      secretKeyRef:
        name: <% .Name %>
        key: CF_KEYPAIR_ID
- name: CF_KEYPAIR_SECRET_KEY
  valueFrom:
      secretKeyRef:
        name: <% .Name %>
        key: CF_KEYPAIR_SECRET_KEY
```

# Acceptance Criteria

# Resources
- https://github.com/commitdev/terraform-aws-zero/blob/main/modules/s3_hosting/main.tf
- https://github.com/commitdev/terraform-aws-zero/blob/0629c7899a0a6f26b89531c5d5a8fff4343bb4c8/modules/database/main.tf#L37-L46
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret
