### ISSUE TITLE
zero-module to support conditions to ignore/include files

### ISSUE THREAD

**Issue by davidcheung** [commitdev/zero#307]
In terraform we can conditionally template out or create resources based on count, 
but in other repos (frontend/backend)we dont have a way to exclude a specific file(or logic) other than inline templating conditions 

to support this we introduce `conditions` in the module file, such as below
**zero-module.yml**
```yml

conditions:
  - type: ignoreFile
    condition:
      field: user_auth ## boolean
      value: false
      files:
        - /templates/src/components/authForm.js
        - /templates/src/pages/auth.js
        - /templates/src/pages/auth.css
        - /templates/src/api/kratos.js

```
