### ISSUE TITLE
Create helm chart for zero-notification-service

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#325]
To make it easy to deploy during setting up zero infra we should support deploying this service via helm.
A new helm chart should be built each time a release is published, and should be made available as a repository using github pages.

Here's an example I started but haven't tested yet:

```
name: Release Helm Chart

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

```
