### ISSUE TITLE
Change module options enum from list to map

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#346]
Currently in module.yml, parameter options for an enum are provided as a list of values to choose from. This is limiting because the name has to be both a user-friendly name and an identifier.
Switching to a map will allow us to have both a machine-friendly identifier and a user-friendly name.

For example:
Old:
```yaml
  - field: database
    label: Database engine to use (postgres)
    options:
      - "postgres"
      - "mysql"
```

New:
```yaml
  - field: database
    label: Database engine to use
    options:
      postgres: "PostgreSQL"
      mysql: "MySQL"
```
