### ISSUE TITLE
Add conditional parameters support to module config

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#348]
Individual parameter prompts need to be able to specify that they are conditional on the value of a previous prompt.
We should also be able to specify that a parameter is only for making a conditional decision and should not be included in the project yaml. See `includeInProjectFile` below
Sample yaml:

```yaml
  - field: useExistingAwsProfile
    label: "Use credentials from an existing AWS profile?"
    default: yes
    includeInProjectFile: no
    options:
        yes: "Yes"
        no: "No"
  - field: awsAccessKeyId
    label: Enter your GitHub Access Token
    conditionalKey: useExistingAwsProfile
    conditionalValue: no
```
