### ISSUE TITLE
Remove credentials file, merge credentials prompts into parameters

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#349]
Remove support for credentials file

Add any previous credentials prompts to zero-modules

Add support for modules file to specify special types where the zero application will render the prompt. 
For example, aws credentials - we want to ask if they want to choose an existing profile or enter their own creds. If they want to choose a profile we need to load the profiles, then get the keys when they pick one. This logic already exists in the app and I think it would be too complex to try to move all of it into the yaml.

There will be cases where credentials need to be used in `execute` commands for subsequent parameters. For example, to get the `accountId` we call `aws sts` which requires the AWS credentials. Right now we have the aws creds specified as a struct with the env var name in the metadata and we have a function to extract it. 
In the new way, maybe we specify the env var name in the yaml and then for each prompt, find any previously entered values that have an env var name, collect those and pass them as env vars to any `execute` commands?

Also need to make sure the ordering is such that the ones that depend on credentials come after the ones that collect the credentials, but maybe this can just be handled by making sure the ordering is preserved from the yaml file.

Also need the ability to make prompts conditional (#348)

Change `module.yaml` files in existing modules to support new features.

Sample yaml based on these requirements:
```yaml
  - field: useExistingAwsProfile
    label: "Use credentials from an existing AWS profile?"
    default: yes
    includeInProjectFile: no
    options:
        yes: "Yes"
        no: "No"
  - field: awsAccessKeyId
    label: Enter your GitHub Access Token
    conditionalKey: useExistingAwsProfile
    conditionalValue: no
    envVarName: AWS_ACCESS_KEY_ID
  - field: awsProfile
    type: awsProfileLookup
    conditionalKey: useExistingAwsProfile
    conditionalValue: yes
    includeInProjectFile: no
```
