### ISSUE TITLE
Spike - Investigate Stripe for adding support to Zero

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#360]

**Comment by davidcheung** [comment]
with new options we can actually conditional prompt users in sequence such as
along with this https://github.com/franckverrot/terraform-provider-stripe 

```yml
Enable billing with Stripe:
- yes 
- no

## From which (infra/backend) repo setup a terraform to run to create and manage provider/plans/webhook
stripe api key: (if enabled) 
  - SANDBOX_API_KEY # creates in secret manager

Setup example subscription plan: (if enabled) 
- yes 
- no
## TODO: 
## - Backend api call to subscript current user
## - terraform module to allow multiple `products` to be created from local array

Setup example stripe webhook 
- yes 
- no
## TODO: 
## - backend endpoint to receive webhooks then just print the webhook details?


## TODO: frontned
button to trigger subscription plan flow 
```
