### ISSUE TITLE
Remove the secrets.yml from the generated files, or add .gitignore

### ISSUE THREAD

**Issue by Direside** [commitdev/zero#95]
When you run the create command, it puts your AWS and CircleCI credentials in a plain text file in the repo that is ready to be committed. To avoid this accidentally being published, we should remove it and instead just save a reference to the profile location.

Current:
```yml
aws:
  accesskeyid: REDACTED
  secretaccesskey: REDACTED
circlecikey: REDACTED
githubtoken: REDACTED
```

Proposed:
```yml
aws:
  profile: default
  location: ~/.aws/credentials
```
